function execute() {
    return Response.success([
        {title: "Truyện Hot", input: "https://botruyen.vip/danh-sach/truyen-moi", script: "new.js"},
        {title: "Tiên Hiệp", input:  "https://botruyen.vip/i-category/tien-hiep", script: "gen.js"},
        {title: "Kiếm Hiệp", input:  "https://botruyen.vip/i-category/kiem-hiep", script: "gen.js"},
        {title: "Huyền Ảo", input:  "https://botruyen.vip/i-category/huyen-ao", script: "gen.js"},
        {title: "Truyện Main Ác", input:  "https://botruyen.vip/i-category/truyen-main-ac", script: "gen.js"},
        {title: "Đô Thị", input:  "https://botruyen.vip/i-category/do-thi", script: "gen.js"},
        {title: "Võng Du", input:  "https://botruyen.vip/i-category/vong-du", script: "gen.js"},
        {title: "Harem", input:  "https://botruyen.vip/i-category/harem-truyen-nhieu-vo", script: "gen.js"},
        {title: "Dị Giới", input:  "https://botruyen.vip/i-category/di-gioi", script: "gen.js"},
        {title: "Xuyên Không", input:  "https://botruyen.vip/i-category/xuyen-khong", script: "gen.js"},
        {title: "Dị Năng", input:  "https://botruyen.vip/i-category/di-nang", script: "gen.js"},
        {title: "Truyện Voz", input:  "https://botruyen.vip/i-category/truyen-voz", script: "gen.js"},
        {title: "Truyện Teen", input:  "https://botruyen.vip/i-category/truyen-teen", script: "gen.js"},
        {title: "Trọng Sinh", input:  "https://botruyen.vip/i-category/truyen-trong-sinh", script: "gen.js"},
        {title: "Sắc Hiệp", input:  "https://botruyen.vip/i-category/sac-hiep", script: "gen.js"},
        {title: "Dị Năng", input:  "https://botruyen.vip/i-category/di-nang", script: "gen.js"},
        {title: "Đam Mỹ", input:  "https://botruyen.vip/i-category/dam-my", script: "gen.js"},
        {title: "Đồng Nhân", input:  "https://botruyen.vip/i-category/truyen-dong-nhan", script: "gen.js"},
        {title: "Hệ Thống", input:  "https://botruyen.vip/i-category/truyen-he-thong", script: "gen.js"},
        {title: "Mạt Thế", input:  "https://botruyen.vip/i-category/truyen-mat-the", script: "gen.js"},
        {title: "Khoa Huyễn", input:  "https://botruyen.vip/i-category/truyen-khoa-huyen", script: "gen.js"},
        {title: "Linh Dị", input:  "https://botruyen.vip/i-category/linh-di", script: "gen.js"},
        {title: "Quân Sự", input:  "https://botruyen.vip/i-category/truyen-quan-su", script: "gen.js"},
        {title: "Quan Trường", input:  "https://botruyen.vip/i-category/truyen-quan-truong", script: "gen.js"},
        {title: "Lịch Sử", input:  "https://botruyen.vip/i-category/truyen-lich-su", script: "gen.js"},
        {title: "Ngôn Tình", input:  "https://botruyen.vip/i-category/ngon-tinh", script: "gen.js"},
        {title: "Ngôn Tình Sủng", input:  "https://botruyen.vip/nhom-dich/ngon-tinh-sung", script: "gen.js"},
        {title: "Cung Đấu", input:  "https://botruyen.vip/i-category/truyen-cung-dau", script: "gen.js"},
        {title: "Nữ Cường", input:  "https://botruyen.vip/i-category/truyen-nu-cuong", script: "gen.js"},
        {title: "Nữ Hiệp", input:  "https://botruyen.vip/i-category/truyen-nu-hiep", script: "gen.js"},
        {title: "Nữ Phụ", input:  "https://botruyen.vip/i-category/truyen-nu-phu", script: "gen.js"},
        {title: "Bách Hợp", input:  "https://botruyen.vip/i-category/truyen-bach-hop", script: "gen.js"},
        {title: "Trinh Thám", input:  "https://botruyen.vip/i-category/truyen-trinh-tham", script: "gen.js"},
        {title: "Cổ Đại", input:  "https://botruyen.vip/i-category/truyen-co-dai", script: "gen.js"},
        {title: "Điền Văn", input:  "https://botruyen.vip/i-category/dien-van", script: "gen.js"},
        {title: "Light Novel", input:  "https://botruyen.vip/i-category/light-novel", script: "gen.js"},
        {title: "Phương Tây", input:  "https://botruyen.vip/i-category/tieu-thuyet-phuong-tay", script: "gen.js"}
    ]);
}