function execute() {
    return Response.success([
        {title: "言情", input:  "https://www.twbook.cc/bookstack/?cid=1", script: "zen.js"},
        {title: "歷史", input:  "https://www.twbook.cc/bookstack/?cid=2", script: "zen.js"},
        {title: "其他", input:  "https://www.twbook.cc/bookstack/?cid=3", script: "zen.js"},
        {title: "都市", input:  "https://www.twbook.cc/bookstack/?cid=4", script: "zen.js"},
        {title: "玄幻", input:  "https://www.twbook.cc/bookstack/?cid=5", script: "zen.js"},
        {title: "體育", input:  "https://www.twbook.cc/bookstack/?cid=6", script: "zen.js"},
        {title: "武俠", input:  "https://www.twbook.cc/bookstack/?cid=7", script: "zen.js"},
        {title: "穿越", input:  "https://www.twbook.cc/bookstack/?cid=8", script: "zen.js"},
        {title: "網游", input:  "https://www.twbook.cc/bookstack/?cid=9", script: "zen.js"},
        {title: "科幻", input:  "https://www.twbook.cc/bookstack/?cid=10", script: "zen.js"},
        {title: "仙俠", input:  "https://www.twbook.cc/bookstack/?cid=11", script: "zen.js"},
        {title: "劇情", input:  "https://www.twbook.cc/bookstack/?cid=12", script: "zen.js"},
        {title: "校園", input:  "https://www.twbook.cc/bookstack/?cid=13", script: "zen.js"},
        {title: "詩文", input:  "https://www.twbook.cc/bookstack/?cid=14", script: "zen.js"},
        {title: "靈異", input:  "https://www.twbook.cc/bookstack/?cid=15", script: "zen.js"},
        {title: "職場", input:  "https://www.twbook.cc/bookstack/?cid=16", script: "zen.js"},
        {title: "偵探", input:  "https://www.twbook.cc/bookstack/?cid=17", script: "zen.js"},
        {title: "軍事", input:  "https://www.twbook.cc/bookstack/?cid=18", script: "zen.js"},
        {title: "懸疑", input:  "https://www.twbook.cc/bookstack/?cid=19", script: "zen.js"},
        {title: "耽美", input:  "https://www.twbook.cc/bookstack/?cid=21", script: "zen.js"},
        {title: "名著", input:  "https://www.twbook.cc/bookstack/?cid=22", script: "zen.js"},
        {title: "輕小說", input:  "https://www.twbook.cc/bookstack/?cid=24", script: "zen.js"},
        {title: "遊戲", input:  "https://www.twbook.cc/bookstack/?cid=25", script: "zen.js"},
        {title: "奇幻", input:  "https://www.twbook.cc/bookstack/?cid=26", script: "zen.js"},
        {title: "其它", input:  "https://www.twbook.cc/bookstack/?cid=29", script: "zen.js"},
        {title: "都市小說", input:  "https://www.twbook.cc/bookstack/?cid=30", script: "zen.js"},
        {title: "歷史小說", input:  "https://www.twbook.cc/bookstack/?cid=31", script: "zen.js"},
        {title: "玄幻小說", input:  "https://www.twbook.cc/bookstack/?cid=32", script: "zen.js"},
        {title: "科幻小說", input:  "https://www.twbook.cc/bookstack/?cid=33", script: "zen.js"},
        {title: "修真", input:  "https://www.twbook.cc/bookstack/?cid=34", script: "zen.js"},
        {title: "都市言情", input:  "https://www.twbook.cc/bookstack/?cid=35", script: "zen.js"},
        {title: "玄幻奇幻", input:  "https://www.twbook.cc/bookstack/?cid=36", script: "zen.js"},
        {title: "武俠仙俠", input:  "https://www.twbook.cc/bookstack/?cid=37", script: "zen.js"},
        {title: "歷史軍事", input:  "https://www.twbook.cc/bookstack/?cid=38", script: "zen.js"},
        {title: "科幻靈異", input:  "https://www.twbook.cc/bookstack/?cid=39", script: "zen.js"},
        {title: "網游競技", input:  "https://www.twbook.cc/bookstack/?cid=40", script: "zen.js"},
        {title: "女頻頻道", input:  "https://www.twbook.cc/bookstack/?cid=41", script: "zen.js"},
        {title: "女頻", input:  "https://www.twbook.cc/bookstack/?cid=42", script: "zen.js"},
        {title: "同人", input:  "https://www.twbook.cc/bookstack/?cid=43", script: "zen.js"},
        {title: "官場", input:  "https://www.twbook.cc/bookstack/?cid=50", script: "zen.js"},
        {title: "未分", input:  "https://www.twbook.cc/bookstack/?cid=51", script: "zen.js"}

    ]);
}