function execute() {
    return Response.success([
        {title: "Fan-Fiction", input: "https://www.readwn.com//list/fan-fiction/all-newstime-", script: "gen.js"},
        {title: "Action", input: "https://www.readwn.com//list/action/all-newstime-", script: "gen.js"},
        {title: "Adventure", input: "https://www.readwn.com//list/adventure/all-newstime-", script: "gen.js"},
        {title: "Comedy", input: "https://www.readwn.com//list/comedy/all-newstime-", script: "gen.js"},
        {title: "Contemporary Romance", input: "https://www.readwn.com//list/contemporary-romance/all-newstime-", script: "gen.js"},
        {title: "Drama", input: "https://www.readwn.com//list/drama/all-newstime-", script: "gen.js"},
        {title: "Eastern Fantasy", input: "https://www.readwn.com//list/eastern-fantasy/all-newstime-", script: "gen.js"},
        {title: "Ecchi", input: "https://www.readwn.com//list/ecchi/all-newstime-", script: "gen.js"},
        {title: "Fantasy", input: "https://www.readwn.com//list/fantasy/all-newstime-", script: "gen.js"},
        {title: "Fantasy Romance", input: "https://www.readwn.com//list/fantasy-romance/all-newstime-", script: "gen.js"},
        {title: "Gender Bender", input: "https://www.readwn.com//list/gender-bender/all-newstime-", script: "gen.js"},
        {title: "Harem", input: "https://www.readwn.com//list/harem/all-newstime-", script: "gen.js"},
        {title: "Historical", input: "https://www.readwn.com//list/historical/all-newstime-", script: "gen.js"},
        {title: "Horror", input: "https://www.readwn.com//list/horror/all-newstime-", script: "gen.js"},
        {title: "Josei", input: "https://www.readwn.com//list/josei/all-newstime-", script: "gen.js"},
        {title: "Lolicon", input: "https://www.readwn.com//list/lolicon/all-newstime-", script: "gen.js"},
        {title: "Magical Realism", input: "https://www.readwn.com//list/magical-realism/all-newstime-", script: "gen.js"},
        {title: "Martial Arts", input: "https://www.readwn.com//list/martial-arts/all-newstime-", script: "gen.js"},
        {title: "Mature", input: "https://www.readwn.com//list/mature/all-newstime-", script: "gen.js"},
        {title: "Mecha", input: "https://www.readwn.com//list/mecha/all-newstime-", script: "gen.js"},
        {title: "Mystery", input: "https://www.readwn.com//list/mystery/all-newstime-", script: "gen.js"},
        {title: "Psychological", input: "https://www.readwn.com//list/psychological/all-newstime-", script: "gen.js"},
        {title: "Romance", input: "https://www.readwn.com//list/romance/all-newstime-", script: "gen.js"},
        {title: "School Life", input: "https://www.readwn.com//list/school-life/all-newstime-", script: "gen.js"},
        {title: "Sci-fi", input: "https://www.readwn.com//list/sci-fi/all-newstime-", script: "gen.js"},
        {title: "Seinen", input: "https://www.readwn.com//list/seinen/all-newstime-", script: "gen.js"},
        {title: "Shoujo", input: "https://www.readwn.com//list/shoujo/all-newstime-", script: "gen.js"},
        {title: "Shounen", input: "https://www.readwn.com//list/shounen/all-newstime-", script: "gen.js"},
        {title: "Shounen Ai", input: "https://www.readwn.com//list/shounen-ai/all-newstime-", script: "gen.js"},
        {title: "Slice of Life", input: "https://www.readwn.com//list/slice-of-life/all-newstime-", script: "gen.js"},
        {title: "Smut", input: "https://www.readwn.com//list/smut/all-newstime-", script: "gen.js"},
        {title: "Sports", input: "https://www.readwn.com//list/sports/all-newstime-", script: "gen.js"},
        {title: "Supernatural", input: "https://www.readwn.com//list/supernatural/all-newstime-", script: "gen.js"},
        {title: "Tragedy", input: "https://www.readwn.com//list/tragedy/all-newstime-", script: "gen.js"},
        {title: "Video Games", input: "https://www.readwn.com//list/video-games/all-newstime-", script: "gen.js"},
        {title: "Wuxia", input: "https://www.readwn.com//list/wuxia/all-newstime-", script: "gen.js"},
        {title: "Xianxia", input: "https://www.readwn.com//list/xianxia/all-newstime-", script: "gen.js"},
        {title: "Xuanhuan", input: "https://www.readwn.com//list/xuanhuan/all-newstime-", script: "gen.js"},
        {title: "Yaoi", input: "https://www.readwn.com//list/yaoi/all-newstime-", script: "gen.js"},
        {title: "Two-dimensional", input: "https://www.readwn.com//list/two-dimensional/all-newstime-", script: "gen.js"},
        {title: "Erciyuan", input: "https://www.readwn.com//list/erciyuan/all-newstime-", script: "gen.js"},
        {title: "Adult", input: "https://www.readwn.com//list/adult/all-newstime-", script: "gen.js"},
        {title: "Game", input: "https://www.readwn.com//list/game/all-newstime-", script: "gen.js"},
        {title: "Military", input: "https://www.readwn.com//list/military/all-newstime-", script: "gen.js"},
        {title: "Urban Life", input: "https://www.readwn.com//list/urban-life/all-newstime-", script: "gen.js"},
        {title: "Yuri", input: "https://www.readwn.com//list/yuri/all-newstime-", script: "gen.js"},
        {title: "Chinese", input: "https://www.readwn.com//list/chinese/all-newstime-", script: "gen.js"},
        {title: "Korean", input: "https://www.readwn.com//list/korean/all-newstime-", script: "gen.js"},
        {title: "Japanese", input: "https://www.readwn.com//list/japanese/all-newstime-", script: "gen.js"},
        {title: "Hentai", input: "https://www.readwn.com//list/hentai/all-newstime-", script: "gen.js"},
        {title: "Isekai", input: "https://www.readwn.com//list/isekai/all-newstime-", script: "gen.js"},
        {title: "Magic", input: "https://www.readwn.com//list/magic/all-newstime-", script: "gen.js"},
        {title: "Shoujo Ai", input: "https://www.readwn.com//list/shoujo-ai/all-newstime-", script: "gen.js"},
        {title: "Urban", input: "https://www.readwn.com//list/urban/all-newstime-", script: "gen.js"},
        {title: "Virtual Reality", input: "https://www.readwn.com//list/virtual-reality/all-newstime-", script: "gen.js"},
        {title: "Faloo", input: "https://www.readwn.com//list/faloo/all-newstime-", script: "gen.js"},
        {title: "Wuxia Xianxia", input: "https://www.readwn.com//list/wuxia_xianxia/all-newstime-", script: "gen.js"},
        {title: "Official Circles", input: "https://www.readwn.com//list/official_circles/all-newstime-", script: "gen.js"},
        {title: "Science Fiction", input: "https://www.readwn.com//list/science_fiction/all-newstime-", script: "gen.js"},
        {title: "Suspense Thriller", input: "https://www.readwn.com//list/suspense_thriller/all-newstime-", script: "gen.js"},
        {title: "Travel Through Time", input: "https://www.readwn.com//list/travel_through_time/all-newstime-", script: "gen.js"},

    ]);
}