function execute() {
    return Response.success([
        {title: "传记回忆", input:  "https://www.yodu.org/zhuanjihuiyi/", script: "gen.js"},
        {title: "英文读本", input:  "https://www.yodu.org/yingwenduben/", script: "gen.js"},
        {title: "杂文随笔", input:  "https://www.yodu.org/zawensuibi/", script: "gen.js"},
        {title: "经典言情", input:  "https://www.yodu.org/jingdianyanqing/", script: "gen.js"},
        {title: "经典历史", input:  "https://www.yodu.org/jingdianlishi/", script: "gen.js"},
        {title: "侦探推理", input:  "https://www.yodu.org/zhentantuili/", script: "gen.js"},
        {title: "惊悚悬疑", input:  "https://www.yodu.org/jingsongxuanyi/", script: "gen.js"},
        {title: "网络玄幻", input:  "https://www.yodu.org/wangluoxuanhuan/", script: "gen.js"},
        {title: "寓言童话", input:  "https://www.yodu.org/yuyantonghua/", script: "gen.js"},
        {title: "青春都市", input:  "https://www.yodu.org/qingchundushi/", script: "gen.js"},
        {title: "社会心理", input:  "https://www.yodu.org/shehuixinli/", script: "gen.js"},
        {title: "外国小说", input:  "https://www.yodu.org/waiguoxiaoshuo/", script: "gen.js"},
        {title: "经典科幻", input:  "https://www.yodu.org/jingdiankehuan/", script: "gen.js"},
        {title: "当代小说", input:  "https://www.yodu.org/dangdaixiaoshuo/", script: "gen.js"},
        {title: "经典武侠", input:  "https://www.yodu.org/jingdianwuxia/", script: "gen.js"},
        {title: "纪实报告", input:  "https://www.yodu.org/jishibaogao/", script: "gen.js"},
        {title: "世界历史", input:  "https://www.yodu.org/shijielishi/", script: "gen.js"},
        {title: "中国历史", input:  "https://www.yodu.org/zhongguolishi/", script: "gen.js"},
        {title: "科普学习", input:  "https://www.yodu.org/kepuxuexi/", script: "gen.js"},
        {title: "诗歌戏曲", input:  "https://www.yodu.org/shigexiqu/", script: "gen.js"},
        {title: "宗教哲学", input:  "https://www.yodu.org/zongjiaozhexue/", script: "gen.js"},
        {title: "文学理论", input:  "https://www.yodu.org/wenxuelilun/", script: "gen.js"},
        {title: "日语读物", input:  "https://www.yodu.org/riyuduwu/", script: "gen.js"},
        {title: "作品集", input:  "https://www.yodu.org/zuopinji/", script: "gen.js"},
        {title: "国学古籍", input:  "https://www.yodu.org/guoxueguji/", script: "gen.js"},
        {title: "战争军事", input:  "https://www.yodu.org/zhanzhengjunshi/", script: "gen.js"},
        {title: "政治经济", input:  "https://www.yodu.org/zhengzhijingji/", script: "gen.js"},
        {title: "古典文学", input:  "https://www.yodu.org/gudianwenxue/", script: "gen.js"},
        {title: "现代小说", input:  "https://www.yodu.org/xiandaixiaoshuo/", script: "gen.js"},
        {title: "官场小说", input:  "https://www.yodu.org/guanchangxiaoshuo/", script: "gen.js"},
        {title: "轻小说", input:  "https://www.yodu.org/qingxiaoshuo/", script: "gen.js"}
    ]);
}