function execute() {
    return Response.success([
        {title: "甜文", input:  "http://www.fuxsb.com/tags-197-", script: "zen.js"},
        {title: "情有独钟", input:  "http://www.fuxsb.com/tags-3-", script: "zen.js"},
        {title: "爽文", input:  "http://www.fuxsb.com/tags-183-", script: "zen.js"},
        {title: "强强", input:  "http://www.fuxsb.com/tags-170-", script: "zen.js"},
        {title: "娱乐圈", input:  "http://www.fuxsb.com/tags-219-", script: "zen.js"},
        {title: "重生", input:  "http://www.fuxsb.com/tags-2-", script: "zen.js"},
        {title: "穿越时空", input:  "http://www.fuxsb.com/tags-222-", script: "zen.js"},
        {title: "穿书", input:  "http://www.fuxsb.com/tags-225-", script: "zen.js"},
        {title: "灵异神怪", input:  "http://www.fuxsb.com/tags-4-", script: "zen.js"},
        {title: "系统", input:  "http://www.fuxsb.com/tags-171-", script: "zen.js"},
        {title: "豪门世家", input:  "http://www.fuxsb.com/tags-206-", script: "zen.js"},
        {title: "生子", input:  "http://www.fuxsb.com/tags-15-", script: "zen.js"},
        {title: "快穿", input:  "http://www.fuxsb.com/tags-218-", script: "zen.js"},
        {title: "仙侠修真", input:  "http://www.fuxsb.com/tags-224-", script: "zen.js"},
        {title: "年下", input:  "http://www.fuxsb.com/tags-192-", script: "zen.js"},
        {title: "种田文", input:  "http://www.fuxsb.com/tags-502-", script: "zen.js"},
        {title: "星际", input:  "http://www.fuxsb.com/tags-202-", script: "zen.js"},
        {title: "都市情缘", input:  "http://www.fuxsb.com/tags-17-", script: "zen.js"},
        {title: "校园", input:  "http://www.fuxsb.com/tags-221-", script: "zen.js"},
        {title: "ABO", input:  "http://www.fuxsb.com/tags-191-", script: "zen.js"},
        {title: "幻想空间", input:  "http://www.fuxsb.com/tags-234-", script: "zen.js"},
        {title: "HE", input:  "http://www.fuxsb.com/tags-677-", script: "zen.js"},
        {title: "破镜重圆", input:  "http://www.fuxsb.com/tags-11-", script: "zen.js"},
        {title: "天作之合", input:  "http://www.fuxsb.com/tags-196-", script: "zen.js"},
        {title: "欢喜冤家", input:  "http://www.fuxsb.com/tags-194-", script: "zen.js"},
        {title: "甜宠", input:  "http://www.fuxsb.com/tags-730-", script: "zen.js"},
        {title: "宫廷侯爵", input:  "http://www.fuxsb.com/tags-263-", script: "zen.js"},
        {title: "打脸", input:  "http://www.fuxsb.com/tags-214-", script: "zen.js"},
        {title: "短篇", input:  "http://www.fuxsb.com/tags-619-", script: "zen.js"},
        {title: "无限流", input:  "http://www.fuxsb.com/tags-216-", script: "zen.js"},
        {title: "天之骄子", input:  "http://www.fuxsb.com/tags-228-", script: "zen.js"},
        {title: "综漫", input:  "http://www.fuxsb.com/tags-249-", script: "zen.js"},
        {title: "游戏网游", input:  "http://www.fuxsb.com/tags-242-", script: "zen.js"},
        {title: "现代架空", input:  "http://www.fuxsb.com/tags-396-", script: "zen.js"},
        {title: "无CP", input:  "http://www.fuxsb.com/tags-1010-", script: "zen.js"},
        {title: "励志人生", input:  "http://www.fuxsb.com/tags-223-", script: "zen.js"},
        {title: "末世", input:  "http://www.fuxsb.com/tags-435-", script: "zen.js"},
        {title: "美食", input:  "http://www.fuxsb.com/tags-488-", script: "zen.js"},
        {title: "异能", input:  "http://www.fuxsb.com/tags-284-", script: "zen.js"},
        {title: "年上", input:  "http://www.fuxsb.com/tags-292-", script: "zen.js"},
        {title: "萌宠", input:  "http://www.fuxsb.com/tags-870-", script: "zen.js"},
        {title: "架空", input:  "http://www.fuxsb.com/tags-233-", script: "zen.js"},
        {title: "直播", input:  "http://www.fuxsb.com/tags-601-", script: "zen.js"},
        {title: "狗血", input:  "http://www.fuxsb.com/tags-765-", script: "zen.js"},
        {title: "未来架空", input:  "http://www.fuxsb.com/tags-231-", script: "zen.js"},
        {title: "悬疑推理", input:  "http://www.fuxsb.com/tags-205-", script: "zen.js"},
        {title: "业界精英", input:  "http://www.fuxsb.com/tags-414-", script: "zen.js"},
        {title: "前世今生", input:  "http://www.fuxsb.com/tags-410-", script: "zen.js"},
        {title: "搞笑", input:  "http://www.fuxsb.com/tags-181-", script: "zen.js"},
        {title: "竞技", input:  "http://www.fuxsb.com/tags-246-", script: "zen.js"}

    ]);
}