function execute() {
    return Response.success([
        {title: "全部", input:  "https://www.haitang123.co/category/0/", script: "gen.js"},
        {title: "言情", input:  "https://www.haitang123.co/category/2/", script: "gen.js"},
        {title: "耽美", input:  "https://www.haitang123.co/category/11/", script: "gen.js"},
        {title: "耽美中文", input:  "https://www.haitang123.co/category/42/", script: "gen.js"},
        {title: "百合", input:  "https://www.haitang123.co/category/24/", script: "gen.js"},
        {title: "玄幻", input:  "https://www.haitang123.co/category/4/", script: "gen.js"},
        {title: "高辣", input:  "https://www.haitang123.co/category/1/", script: "gen.js"},
        {title: "都市", input:  "https://www.haitang123.co/category/14/", script: "gen.js"},
        {title: "穿越", input:  "https://www.haitang123.co/category/16/", script: "gen.js"},
        {title: "种田", input:  "https://www.haitang123.co/category/8/", script: "gen.js"},
        {title: "高干", input:  "https://www.haitang123.co/category/5/", script: "gen.js"},
        {title: "私密", input:  "https://www.haitang123.co/category/39/", script: "gen.js"},
        {title: "腹黑", input:  "https://www.haitang123.co/category/6/", script: "gen.js"},
        {title: "历史", input:  "https://www.haitang123.co/category/12/", script: "gen.js"},
        {title: "修真", input:  "https://www.haitang123.co/category/7/", script: "gen.js"},
        {title: "青春", input:  "https://www.haitang123.co/category/13/", script: "gen.js"},
        {title: "武侠", input:  "https://www.haitang123.co/category/17/", script: "gen.js"},
        {title: "网游", input:  "https://www.haitang123.co/category/9/", script: "gen.js"},
        {title: "科幻", input:  "https://www.haitang123.co/category/22/", script: "gen.js"},
        {title: "悬疑", input:  "https://www.haitang123.co/category/15/", script: "gen.js"},
        {title: "经管", input:  "https://www.haitang123.co/category/18/", script: "gen.js"},
        {title: "仙侠", input:  "https://www.haitang123.co/category/25/", script: "gen.js"},
        {title: "侦探", input:  "https://www.haitang123.co/category/40/", script: "gen.js"},
        {title: "恐怖", input:  "https://www.haitang123.co/category/41/", script: "gen.js"},
        {title: "现代", input:  "https://www.haitang123.co/category/20/", script: "gen.js"},
        {title: "游戏", input:  "https://www.haitang123.co/category/28/", script: "gen.js"},
        {title: "竞技", input:  "https://www.haitang123.co/category/33/", script: "gen.js"},
        {title: "灵异", input:  "https://www.haitang123.co/category/29/", script: "gen.js"},
        {title: "军事", input:  "https://www.haitang123.co/category/36/", script: "gen.js"},
        {title: "古代", input:  "https://www.haitang123.co/category/31/", script: "gen.js"},
        {title: "综合", input:  "https://www.haitang123.co/category/27/", script: "gen.js"},
        {title: "其他", input:  "https://www.haitang123.co/category/19/", script: "gen.js"},
        {title: "同人", input:  "https://www.haitang123.co/category/47/", script: "gen.js"},
        {title: "其它", input:  "https://www.haitang123.co/category/37/", script: "gen.js"},
        {title: "仙武", input:  "https://www.haitang123.co/category/45/", script: "gen.js"},
        {title: "二次", input:  "https://www.haitang123.co/category/46/", script: "gen.js"}

    ]);
}