function execute() {
    return Response.success([
        {title: "Tiên Hiệp", input: "https://truyenfull.org/the-loai/tien-hiep/", script: "gen.js"},
        {title: "Kiếm Hiệp", input: "https://truyenfull.org/the-loai/kiem-hiep/", script: "gen.js"},
        {title: "Ngôn Tình", input: "https://truyenfull.org/the-loai/ngon-tinh/", script: "gen.js"},
        {title: "Đô Thị", input: "https://truyenfull.org/the-loai/do-thi/", script: "gen.js"},
        {title: "Quan Trường", input: "https://truyenfull.org/the-loai/quan-truong/", script: "gen.js"},
        {title: "Võng Du", input: "https://truyenfull.org/the-loai/vong-du/", script: "gen.js"},
        {title: "Khoa Huyễn", input: "https://truyenfull.org/the-loai/khoa-huyen/", script: "gen.js"},
        {title: "Hệ Thống", input: "https://truyenfull.org/the-loai/he-thong/", script: "gen.js"},
        {title: "Huyền Huyễn", input: "https://truyenfull.org/the-loai/huyen-huyen/", script: "gen.js"},
        {title: "Dị Giới", input: "https://truyenfull.org/the-loai/di-gioi/", script: "gen.js"},
        {title: "Dị Năng", input: "https://truyenfull.org/the-loai/di-nang/", script: "gen.js"},
        {title: "Quân Sự", input: "https://truyenfull.org/the-loai/quan-su/", script: "gen.js"},
        {title: "Lịch Sử", input: "https://truyenfull.org/the-loai/lich-su/", script: "gen.js"},
        {title: "Xuyên Không", input: "https://truyenfull.org/the-loai/xuyen-khong/", script: "gen.js"},
        {title: "Xuyên Nhanh", input: "https://truyenfull.org/the-loai/xuyen-nhanh/", script: "gen.js"},
        {title: "Trọng Sinh", input: "https://truyenfull.org/the-loai/trong-sinh/", script: "gen.js"},
        {title: "Trinh Thám", input: "https://truyenfull.org/the-loai/trinh-tham/", script: "gen.js"},
        {title: "Thám Hiểm", input: "https://truyenfull.org/the-loai/tham-hiem/", script: "gen.js"},
        {title: "Linh Dị", input: "https://truyenfull.org/the-loai/linh-di/", script: "gen.js"},
        {title: "Sắc", input: "https://truyenfull.org/the-loai/sac/", script: "gen.js"},
        {title: "Ngược", input: "https://truyenfull.org/the-loai/nguoc/", script: "gen.js"},
        {title: "Sủng", input: "https://truyenfull.org/the-loai/sung/", script: "gen.js"},
        {title: "Cung Đấu", input: "https://truyenfull.org/the-loai/cung-dau/", script: "gen.js"},
        {title: "Nữ Cường", input: "https://truyenfull.org/the-loai/nu-cuong/", script: "gen.js"},
        {title: "Gia Đấu", input: "https://truyenfull.org/the-loai/gia-dau/", script: "gen.js"},
        {title: "Đông Phương", input: "https://truyenfull.org/the-loai/dong-phuong/", script: "gen.js"},
        {title: "Đam Mỹ", input: "https://truyenfull.org/the-loai/dam-my/", script: "gen.js"},
        {title: "Bách Hợp", input: "https://truyenfull.org/the-loai/bach-hop/", script: "gen.js"},
        {title: "Hài Hước", input: "https://truyenfull.org/the-loai/hai-huoc/", script: "gen.js"},
        {title: "Điền Văn", input: "https://truyenfull.org/the-loai/dien-van/", script: "gen.js"},
        {title: "Cổ Đại", input: "https://truyenfull.org/the-loai/co-dai/", script: "gen.js"},
        {title: "Mạt Thế", input: "https://truyenfull.org/the-loai/mat-the/", script: "gen.js"},
        {title: "Truyện Teen", input: "https://truyenfull.org/the-loai/truyen-teen/", script: "gen.js"},
        {title: "Phương Tây", input: "https://truyenfull.org/the-loai/phuong-tay/", script: "gen.js"},
        {title: "Nữ Phụ", input: "https://truyenfull.org/the-loai/nu-phu/", script: "gen.js"},
        {title: "Light Novel", input: "https://truyenfull.org/the-loai/light-novel/", script: "gen.js"},
        {title: "Việt Nam", input: "https://truyenfull.org/the-loai/viet-nam/", script: "gen.js"},
        {title: "Đoản Văn", input: "https://truyenfull.org/the-loai/doan-van/", script: "gen.js"},
        {title: "Khác", input: "https://truyenfull.org/the-loai/khac/", script: "gen.js"}
    ]);
}