function execute() {
    return Response.success([
        {title:"男频阅读榜·鉴宝", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=17&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·科幻", input:"/api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=8&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·都市日常", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=261&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·都市修真", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=124&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·奇幻仙侠", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=259&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·历史古代", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=273&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·战神", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=27&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·都市种田", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=263&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·传统玄幻", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=258&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·历史脑洞", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=272&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·悬疑脑洞", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=539&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·都市脑洞", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=262&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·玄幻脑洞", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=257&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·赘婿", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=25&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·神医", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=26&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·悬疑灵异", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=751&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·抗战谍战", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=504&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·游戏体育", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=746&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"男频阅读榜·衍生同人", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=718&rank_version=&gender=1&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·萌宝", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=28&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·玄幻言情", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=248&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·种田", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=23&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·马甲", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=266&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·年代", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=79&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·现言脑洞", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=267&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·宫斗宅斗", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=246&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·悬疑脑洞", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=539&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·古言脑洞", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=253&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·医术", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=247&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·快穿", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=24&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·青春甜宠", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=749&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·豪门爽文", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=745&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·悬疑恋爱", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=747&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·职场婚恋", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=750&rank_version=&gender=0&rankMold=2",script: "gen.js"},
        {title:"女频阅读榜·霸总", input:"api/rank/category/list?app_id=1967&rank_list_type=3&offset={{page}}&limit=20&category_id=748&rank_version=&gender=0&rankMold=2"}
        ]);
}